name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate

  lint:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible + ansible-lint
        run: |
          sudo apt update
          sudo apt install ansible -y
          pip install ansible-lint

      - name: Run ansible-lint
        run: |
          cd ansible
          ansible-lint || true

  zap_scan:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ secrets.EC2_URL }}
